apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql-pod  
spec:
  containers:
  - name: mysql-container
    image: andreleaos/pocmysqldb:1.1
    ports:
    - containerPort: 3306
