apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameapi-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gameapi
  template:
    metadata:
      labels:
        app: gameapi-deploy
    spec:
      containers:
      - name: gameapi
        image: andreleaos/pocwebapi:1.2
        ports:
        - containerPort: 80

